export default {
  "tinyint":"number",
  "smallint":"number",
  "mediumint":"number",
  "int":"number",
  "bigint":"number" ,
  "float":"number" ,
  "double":"number" ,
  "decimal":"number",
  "year":"date" ,
  "time":"date" ,
  "date":"date" ,
  "datetime":"date" ,
  "timestamp":"date" ,
  "char":"input" ,
  "varchar":"input",
  "tinytext":"text-area" ,
  "text":"text-area" ,
  "mediumtext":"text-area" ,
  "longtext":"text-area" ,
  "enum":"input" ,
  "set":"input" ,
  "bit":"input" ,
  "binary":"input" ,
  "varbinary":"input" ,
  "tinyblob":"小blob" ,
  "blob":"input" ,
  "mediumblob":"input" ,
  "longblob":"input"
}